"""Canonical ten-person fixture for Allegory's first vertical slice."""

from __future__ import annotations

from typing import Any

LOCATIONS: list[dict[str, Any]] = [
    {
        "id": "home_1",
        "name": "Willow House",
        "kind": "home",
        "x": 12,
        "y": 18,
        "neighbors": ["west_walk"],
    },
    {
        "id": "home_2",
        "name": "Juniper House",
        "kind": "home",
        "x": 12,
        "y": 72,
        "neighbors": ["west_walk"],
    },
    {
        "id": "home_3",
        "name": "Cedar House",
        "kind": "home",
        "x": 88,
        "y": 18,
        "neighbors": ["east_walk"],
    },
    {
        "id": "home_4",
        "name": "Maple House",
        "kind": "home",
        "x": 88,
        "y": 72,
        "neighbors": ["east_walk"],
    },
    {
        "id": "west_walk",
        "name": "West Walk",
        "kind": "street",
        "x": 28,
        "y": 45,
        "neighbors": ["home_1", "home_2", "town_square"],
    },
    {
        "id": "town_square",
        "name": "Town Square",
        "kind": "street",
        "x": 50,
        "y": 45,
        "neighbors": ["west_walk", "east_walk", "office", "shop", "park", "cafe"],
    },
    {
        "id": "east_walk",
        "name": "East Walk",
        "kind": "street",
        "x": 72,
        "y": 45,
        "neighbors": ["home_3", "home_4", "town_square"],
    },
    {
        "id": "office",
        "name": "Northstar Office",
        "kind": "workplace",
        "x": 50,
        "y": 12,
        "neighbors": ["town_square"],
    },
    {
        "id": "shop",
        "name": "Common Goods",
        "kind": "shop",
        "x": 68,
        "y": 74,
        "neighbors": ["town_square"],
    },
    {
        "id": "park",
        "name": "Pocket Park",
        "kind": "park",
        "x": 34,
        "y": 76,
        "neighbors": ["town_square"],
    },
    {
        "id": "cafe",
        "name": "Corner Cafe",
        "kind": "cafe",
        "x": 50,
        "y": 74,
        "neighbors": ["town_square"],
    },
]

AGENTS: list[dict[str, Any]] = [
    {
        "id": 1,
        "name": "Sara Malik",
        "age": 31,
        "occupation": "product designer",
        "household": "household_1",
        "location_id": "home_1",
        "home_id": "home_1",
        "work_id": "office",
        "budget": 185,
        "sociability": 0.78,
        "price_sensitivity": 0.42,
        "preferences": {"audio": 0.88},
        "relationships": {2: 0.95, 3: 0.72, 6: 0.58},
    },
    {
        "id": 2,
        "name": "Omar Malik",
        "age": 34,
        "occupation": "accountant",
        "household": "household_1",
        "location_id": "home_1",
        "home_id": "home_1",
        "work_id": "office",
        "budget": 145,
        "sociability": 0.52,
        "price_sensitivity": 0.72,
        "preferences": {"audio": 0.58},
        "relationships": {1: 0.95, 5: 0.65, 8: 0.44},
    },
    {
        "id": 3,
        "name": "Maya Chen",
        "age": 27,
        "occupation": "marketing specialist",
        "household": "household_2",
        "location_id": "home_2",
        "home_id": "home_2",
        "work_id": "office",
        "budget": 210,
        "sociability": 0.9,
        "price_sensitivity": 0.35,
        "preferences": {"audio": 0.82},
        "relationships": {1: 0.72, 4: 0.88, 7: 0.71, 10: 0.62},
    },
    {
        "id": 4,
        "name": "Leo Chen",
        "age": 25,
        "occupation": "graduate student",
        "household": "household_2",
        "location_id": "home_2",
        "home_id": "home_2",
        "work_id": "cafe",
        "budget": 95,
        "sociability": 0.73,
        "price_sensitivity": 0.9,
        "preferences": {"audio": 0.92},
        "relationships": {3: 0.88, 6: 0.7, 9: 0.55},
    },
    {
        "id": 5,
        "name": "Priya Shah",
        "age": 42,
        "occupation": "operations manager",
        "household": "household_3",
        "location_id": "home_3",
        "home_id": "home_3",
        "work_id": "office",
        "budget": 260,
        "sociability": 0.64,
        "price_sensitivity": 0.38,
        "preferences": {"audio": 0.62},
        "relationships": {2: 0.65, 6: 0.94, 8: 0.57},
    },
    {
        "id": 6,
        "name": "Ravi Shah",
        "age": 45,
        "occupation": "school teacher",
        "household": "household_3",
        "location_id": "home_3",
        "home_id": "home_3",
        "work_id": "office",
        "budget": 170,
        "sociability": 0.81,
        "price_sensitivity": 0.6,
        "preferences": {"audio": 0.7},
        "relationships": {1: 0.58, 4: 0.7, 5: 0.94, 9: 0.68},
    },
    {
        "id": 7,
        "name": "Elena Garcia",
        "age": 36,
        "occupation": "freelance writer",
        "household": "household_4",
        "location_id": "home_4",
        "home_id": "home_4",
        "work_id": "cafe",
        "budget": 130,
        "sociability": 0.86,
        "price_sensitivity": 0.68,
        "preferences": {"audio": 0.76},
        "relationships": {3: 0.71, 8: 0.93, 10: 0.74},
    },
    {
        "id": 8,
        "name": "Mateo Garcia",
        "age": 38,
        "occupation": "sales representative",
        "household": "household_4",
        "location_id": "home_4",
        "home_id": "home_4",
        "work_id": "office",
        "budget": 225,
        "sociability": 0.84,
        "price_sensitivity": 0.48,
        "preferences": {"audio": 0.66},
        "relationships": {2: 0.44, 5: 0.57, 7: 0.93, 10: 0.61},
    },
    {
        "id": 9,
        "name": "Noah Williams",
        "age": 22,
        "occupation": "retail assistant",
        "household": "household_2",
        "location_id": "home_2",
        "home_id": "home_2",
        "work_id": "shop",
        "budget": 80,
        "sociability": 0.7,
        "price_sensitivity": 0.96,
        "preferences": {"audio": 0.84},
        "relationships": {4: 0.55, 6: 0.68, 10: 0.52},
    },
    {
        "id": 10,
        "name": "Aisha Brooks",
        "age": 29,
        "occupation": "community organizer",
        "household": "household_4",
        "location_id": "home_4",
        "home_id": "home_4",
        "work_id": "park",
        "budget": 155,
        "sociability": 0.95,
        "price_sensitivity": 0.58,
        "preferences": {"audio": 0.73},
        "relationships": {3: 0.62, 7: 0.74, 8: 0.61, 9: 0.52},
    },
]


def products(price: float = 49.0) -> list[dict[str, Any]]:
    return [
        {
            "id": "pulse_mini",
            "name": "Pulse Mini Speaker",
            "category": "audio",
            "price": float(price),
            "store_id": "shop",
        }
    ]


def town_agent_record(agent: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": agent["id"],
        "name": agent["name"],
        "location_id": agent["location_id"],
        "home_id": agent["home_id"],
        "work_id": agent["work_id"],
        "budget": agent["budget"],
        "sociability": agent["sociability"],
        "price_sensitivity": agent["price_sensitivity"],
        "preferences": agent["preferences"],
        "relationships": agent["relationships"],
    }


def person_profile(agent: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": agent["id"],
        "name": agent["name"],
        "age": agent["age"],
        "occupation": agent["occupation"],
        "household": agent["household"],
        "home_id": agent["home_id"],
        "work_id": agent["work_id"],
        "available_spending_budget": agent["budget"],
        "consumer_preferences": agent["preferences"],
        "price_sensitivity": agent["price_sensitivity"],
        "sociability": agent["sociability"],
        "simulation_role": (
            "You are an ordinary resident of Allegory Town, not an assistant or "
            "market researcher. Behave consistently with your profile, limited "
            "knowledge, relationships, budget, routine, and memories. Observe the "
            "town before acting. Use movement, activity, conversation, product "
            "consideration, and purchase tools only when they make sense. You may "
            "ignore information, delay decisions, misunderstand, or keep habits."
        ),
    }
